version: "3"
services:
  bonus-service:
    build:
      context: ./src/BonusServiceApi
      dockerfile: Dockerfile
    container_name: bonus-service
    ports:
      - "8050:8050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8050
      - ConnectionStrings__Default=Host=bonus-db;Port=5432;Database=BonusDb;Username=postgres;Password=postgres
    networks:
      - microservices-network

  bonus-db:
    image: postgres:15-alpine
    container_name: bonus-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bonus-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
  
  #######        
  ticket-service:
    build:
      context: ./src/TicketServiceApi
      dockerfile: Dockerfile
    container_name: ticket-service
    ports:
      - "8070:8070"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8070
      - ConnectionStrings__Default=Host=ticket-db;Port=5433;Database=TicketDb;Username=postgres;Password=postgres
    networks:
      - microservices-network

  ticket-db:
    image: postgres:15-alpine
    container_name: ticket-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ticket-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    command: -p 5433
  
  #######        
  flight-service:
    build:
      context: ./src/FlightServiceApi
      dockerfile: Dockerfile
    container_name: flight-service
    ports:
      - "8060:8060"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8060
      - ConnectionStrings__Default=Host=flight-db;Port=5434;Database=FlightDb;Username=postgres;Password=postgres
    networks:
      - microservices-network

  flight-db:
    image: postgres:15-alpine
    container_name: flight-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - flight-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    command: -p 5434
  #######        
  gateway-service:
    build:
      context: ./src/GatewayService
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  bonus-postgres-data:
  ticket-postgres-data:
  flight-postgres-data:


